-- agent_ledger_export.py により生成(手編集禁止・再生成は scripts/agent_ledger_export.py を実行)。
-- 定時実行スケジュールの唯一の真実源。役職への帰属(agent_ledger)とは分離する。
-- 生成元: projects/tagtech-automation/src/index.ts の cronToTasks / cloudflare/tagtech-cron/src/index.ts の CRON_MAP / cloudflare/vault-intel/wrangler.toml / projects/notify-gw/wrangler.jsonc
-- cron_kind: hourly/daily は期待28日、weekly は 28日=4週で常に4日、monthly のみ窓ごとに再計算する(cron_dom を使う)。

INSERT INTO job_schedule (job_id, worker, cron, cron_kind, cron_dom, expected_days_28d, source) VALUES
  ('notify-gw', 'notify-gw', '5 0 * * *', 'daily', NULL, 28, 'projects/notify-gw/wrangler.jsonc:18'),
  ('tagtech-automation/cbo_sales_report', 'tagtech-automation', '30 2 * * 1', 'weekly', NULL, 4, 'projects/tagtech-automation/src/index.ts:73 (cronToTasks)'),
  ('tagtech-automation/cco_calendar_sync', 'tagtech-automation', '0 21 * * *', 'daily', NULL, 28, 'projects/tagtech-automation/src/index.ts:104 (cronToTasks)'),
  ('tagtech-automation/cco_clip_gen', 'tagtech-automation', '0 8 * * *', 'daily', NULL, 28, 'projects/tagtech-automation/src/index.ts:82 (cronToTasks)'),
  ('tagtech-automation/cdo_data_dashboard', 'tagtech-automation', '10 0 * * *', 'daily', NULL, 28, 'projects/tagtech-automation/src/index.ts:56 (cronToTasks)'),
  ('tagtech-automation/cfo_finance_report', 'tagtech-automation', '30 23 * * *', 'daily', NULL, 28, 'projects/tagtech-automation/src/index.ts:44 (cronToTasks)'),
  ('tagtech-automation/cfo_monthly_report', 'tagtech-automation', '0 0 1 * *', 'monthly', 1, 1, 'projects/tagtech-automation/src/index.ts:124 (cronToTasks)'),
  ('tagtech-automation/channel_activity', 'tagtech-automation', '30 0 * * *', 'daily', NULL, 28, 'projects/tagtech-automation/src/index.ts:60 (cronToTasks)'),
  ('tagtech-automation/chro_health_check', 'tagtech-automation', '0 23 * * *', 'daily', NULL, 28, 'projects/tagtech-automation/src/index.ts:26 (cronToTasks)'),
  ('tagtech-automation/chro_mood_monitor', 'tagtech-automation', '0 15,21,3,9 * * *', 'daily', NULL, 28, 'projects/tagtech-automation/src/index.ts:136 (cronToTasks)'),
  ('tagtech-automation/cio_daily_news', 'tagtech-automation', '0 0 * * *', 'daily', NULL, 28, 'projects/tagtech-automation/src/index.ts:50 (cronToTasks)'),
  ('tagtech-automation/ciso_security_scan', 'tagtech-automation', '5 23 * * *', 'daily', NULL, 28, 'projects/tagtech-automation/src/index.ts:32 (cronToTasks)'),
  ('tagtech-automation/clo_compliance_audit', 'tagtech-automation', '10 23 * * *', 'daily', NULL, 28, 'projects/tagtech-automation/src/index.ts:36 (cronToTasks)'),
  ('tagtech-automation/cmo_sns_evening', 'tagtech-automation', '0 10 * * *', 'daily', NULL, 28, 'projects/tagtech-automation/src/index.ts:91 (cronToTasks)'),
  ('tagtech-automation/cmo_sns_night', 'tagtech-automation', '0 13 * * *', 'daily', NULL, 28, 'projects/tagtech-automation/src/index.ts:99 (cronToTasks)'),
  ('tagtech-automation/cmo_sns_noon', 'tagtech-automation', '0 3 * * *', 'daily', NULL, 28, 'projects/tagtech-automation/src/index.ts:77 (cronToTasks)'),
  ('tagtech-automation/coo_ops_monitor', 'tagtech-automation', '17 * * * *', 'hourly', NULL, 28, 'projects/tagtech-automation/src/index.ts:65 (cronToTasks)'),
  ('tagtech-automation/cpo_platform_review', 'tagtech-automation', '0 14 20 * *', 'monthly', 20, 1, 'projects/tagtech-automation/src/index.ts:119 (cronToTasks)'),
  ('tagtech-automation/cto_notion_sync', 'tagtech-automation', '0 15,3 * * *', 'daily', NULL, 28, 'projects/tagtech-automation/src/index.ts:115 (cronToTasks)'),
  ('tagtech-automation/cto_tech_monitor', 'tagtech-automation', '15 23 * * *', 'daily', NULL, 28, 'projects/tagtech-automation/src/index.ts:40 (cronToTasks)'),
  ('tagtech-automation/daily_standup', 'tagtech-automation', '0 23 * * *', 'daily', NULL, 28, 'projects/tagtech-automation/src/index.ts:27 (cronToTasks)'),
  ('tagtech-automation/ext_audit_skill_review', 'tagtech-automation', '0 0 * * 1', 'weekly', NULL, 4, 'projects/tagtech-automation/src/index.ts:128 (cronToTasks)'),
  ('tagtech-automation/funding_reminder', 'tagtech-automation', '0 0 * * *', 'daily', NULL, 28, 'projects/tagtech-automation/src/index.ts:52 (cronToTasks)'),
  ('tagtech-automation/google_calendar_sync', 'tagtech-automation', '0 22 * * *', 'daily', NULL, 28, 'projects/tagtech-automation/src/index.ts:109 (cronToTasks)'),
  ('tagtech-automation/hn_trends_morning', 'tagtech-automation', '0 22 * * *', 'daily', NULL, 28, 'projects/tagtech-automation/src/index.ts:108 (cronToTasks)'),
  ('tagtech-automation/monthly_fixed_expenses', 'tagtech-automation', '0 0 1 * *', 'monthly', 1, 1, 'projects/tagtech-automation/src/index.ts:123 (cronToTasks)'),
  ('tagtech-automation/notion_task_sync', 'tagtech-automation', '0 15,3 * * *', 'daily', NULL, 28, 'projects/tagtech-automation/src/index.ts:114 (cronToTasks)'),
  ('tagtech-automation/pipeline_daily', 'tagtech-automation', '30 23 * * *', 'daily', NULL, 28, 'projects/tagtech-automation/src/index.ts:45 (cronToTasks)'),
  ('tagtech-automation/pipeline_weekly', 'tagtech-automation', '30 0 * * 1', 'weekly', NULL, 4, 'projects/tagtech-automation/src/index.ts:132 (cronToTasks)'),
  ('tagtech-automation/prompt_self_update_evening', 'tagtech-automation', '0 9 * * *', 'daily', NULL, 28, 'projects/tagtech-automation/src/index.ts:87 (cronToTasks)'),
  ('tagtech-automation/prompt_self_update_morning', 'tagtech-automation', '30 0 * * *', 'daily', NULL, 28, 'projects/tagtech-automation/src/index.ts:61 (cronToTasks)'),
  ('tagtech-automation/prompt_self_update_night', 'tagtech-automation', '0 13 * * *', 'daily', NULL, 28, 'projects/tagtech-automation/src/index.ts:100 (cronToTasks)'),
  ('tagtech-automation/revenue_dashboard', 'tagtech-automation', '0 0 * * *', 'daily', NULL, 28, 'projects/tagtech-automation/src/index.ts:51 (cronToTasks)'),
  ('tagtech-automation/task_pipeline_daily', 'tagtech-automation', '0 23 * * *', 'daily', NULL, 28, 'projects/tagtech-automation/src/index.ts:28 (cronToTasks)'),
  ('tagtech-automation/tiktok_morning', 'tagtech-automation', '0 22 * * *', 'daily', NULL, 28, 'projects/tagtech-automation/src/index.ts:110 (cronToTasks)'),
  ('tagtech-automation/tiktok_night', 'tagtech-automation', '0 12 * * *', 'daily', NULL, 28, 'projects/tagtech-automation/src/index.ts:95 (cronToTasks)'),
  ('tagtech-automation/tiktok_noon', 'tagtech-automation', '0 3 * * *', 'daily', NULL, 28, 'projects/tagtech-automation/src/index.ts:78 (cronToTasks)'),
  ('tagtech-automation/weekly_ceo_meeting', 'tagtech-automation', '0 2 * * 1', 'weekly', NULL, 4, 'projects/tagtech-automation/src/index.ts:69 (cronToTasks)'),
  ('tagtech-automation/youtube_shorts', 'tagtech-automation', '0 9 * * *', 'daily', NULL, 28, 'projects/tagtech-automation/src/index.ts:86 (cronToTasks)'),
  ('tagtech-cron/calendar-pipeline', 'tagtech-cron', '10 20 * * *', 'daily', NULL, 28, 'cloudflare/tagtech-cron/src/index.ts:78 (CRON_MAP)'),
  ('tagtech-cron/cxo-worker', 'tagtech-cron', '47 21 * * *', 'daily', NULL, 28, 'cloudflare/tagtech-cron/src/index.ts:80 (CRON_MAP)'),
  ('tagtech-cron/daily-standup', 'tagtech-cron', '0 23 * * *', 'daily', NULL, 28, 'cloudflare/tagtech-cron/src/index.ts:82 (CRON_MAP)'),
  ('tagtech-cron/digest-watch', 'tagtech-cron', '0 1 * * *', 'daily', NULL, 28, 'cloudflare/tagtech-cron/src/index.ts:87 (CRON_MAP)'),
  ('tagtech-cron/funding-reminder', 'tagtech-cron', '0 0 * * *', 'daily', NULL, 28, 'cloudflare/tagtech-cron/src/index.ts:84 (CRON_MAP)'),
  ('tagtech-cron/ga4-report', 'tagtech-cron', '10 0 * * SUN', 'weekly', NULL, 4, 'cloudflare/tagtech-cron/src/index.ts:93 (CRON_MAP)'),
  ('tagtech-cron/heartbeat', 'tagtech-cron', '5 0 * * *', 'daily', NULL, 28, 'cloudflare/tagtech-cron/src/index.ts:85 (CRON_MAP)'),
  ('tagtech-cron/hn-trends', 'tagtech-cron', '0 22 * * *', 'daily', NULL, 28, 'cloudflare/tagtech-cron/src/index.ts:81 (CRON_MAP)'),
  ('tagtech-cron/notion-to-calendar', 'tagtech-cron', '30 20 * * *', 'daily', NULL, 28, 'cloudflare/tagtech-cron/src/index.ts:79 (CRON_MAP)'),
  ('tagtech-cron/pipeline-daily', 'tagtech-cron', '30 23 * * *', 'daily', NULL, 28, 'cloudflare/tagtech-cron/src/index.ts:83 (CRON_MAP)'),
  ('tagtech-cron/pipeline-weekly', 'tagtech-cron', '30 0 * * SUN', 'weekly', NULL, 4, 'cloudflare/tagtech-cron/src/index.ts:94 (CRON_MAP)'),
  ('tagtech-cron/prompt-self-update-evening', 'tagtech-cron', '0 9 * * *', 'daily', NULL, 28, 'cloudflare/tagtech-cron/src/index.ts:89 (CRON_MAP)'),
  ('tagtech-cron/prompt-self-update-morning', 'tagtech-cron', '30 0 * * *', 'daily', NULL, 28, 'cloudflare/tagtech-cron/src/index.ts:86 (CRON_MAP)'),
  ('tagtech-cron/prompt-self-update-night', 'tagtech-cron', '0 13 * * *', 'daily', NULL, 28, 'cloudflare/tagtech-cron/src/index.ts:91 (CRON_MAP)'),
  ('tagtech-cron/reddit-trends', 'tagtech-cron', '30 22 * * SUN', 'weekly', NULL, 4, 'cloudflare/tagtech-cron/src/index.ts:95 (CRON_MAP)'),
  ('tagtech-cron/revenue-dashboard', 'tagtech-cron', '0 0 * * *', 'daily', NULL, 28, 'cloudflare/tagtech-cron/src/index.ts:84 (CRON_MAP)'),
  ('tagtech-cron/seo-checker', 'tagtech-cron', '0 0 * * SUN', 'weekly', NULL, 4, 'cloudflare/tagtech-cron/src/index.ts:92 (CRON_MAP)'),
  ('tagtech-cron/sns-metrics', 'tagtech-cron', '5 0 * * *', 'daily', NULL, 28, 'cloudflare/tagtech-cron/src/index.ts:85 (CRON_MAP)'),
  ('tagtech-cron/task-pipeline', 'tagtech-cron', '0 23 * * *', 'daily', NULL, 28, 'cloudflare/tagtech-cron/src/index.ts:82 (CRON_MAP)'),
  ('tagtech-cron/tiktok-0700', 'tagtech-cron', '0 22 * * *', 'daily', NULL, 28, 'cloudflare/tagtech-cron/src/index.ts:81 (CRON_MAP)'),
  ('tagtech-cron/tiktok-1200', 'tagtech-cron', '0 3 * * *', 'daily', NULL, 28, 'cloudflare/tagtech-cron/src/index.ts:88 (CRON_MAP)'),
  ('tagtech-cron/tiktok-2100', 'tagtech-cron', '0 12 * * *', 'daily', NULL, 28, 'cloudflare/tagtech-cron/src/index.ts:90 (CRON_MAP)'),
  ('tagtech-cron/youtube-shorts', 'tagtech-cron', '0 9 * * *', 'daily', NULL, 28, 'cloudflare/tagtech-cron/src/index.ts:89 (CRON_MAP)'),
  ('vault-intel/hn-morning', 'vault-intel', '30 22 * * *', 'daily', NULL, 28, 'cloudflare/vault-intel/wrangler.toml:7');
